### ISSUE TITLE
LWW Set ?

### ISSUE THREAD

**Issue by benoitc** [basho/riak_dt#101]
Do you plan to provide an implementation of lwwset ?

**Comment by russelldb** [comment]
Nope, I hadn't planned it. Is it useful? Pretty simple to make. I can probably make one this weekend, unless you want to do it?

**Comment by russelldb** [comment]
I think I like the Roshi one as documented here - https://github.com/soundcloud/roshi

**Comment by benoitc** [comment]
I can try. But i need to become familiar with the code, so you will be probably faster than me ;)

**Comment by russelldb** [comment]
Well, I quite like the idea of making one like the Roshi one linked above, so I'll give it a go.

**Comment by russelldb** [comment]
Out of interest: what use is this CRDT? I can't help thinking it is larger than the ORSWOT (since once added an item is never really removed.)

**Comment by russelldb** [comment]
Should this LWWSet allow "dombstoning?" That is, removing an element that is not present?

**Comment by russelldb** [comment]
Spoke with Roshi author (https://github.com/soundcloud/roshi/issues/24) and they allow doomstones, so now riak_dt LWWSet does too.

**Comment by russelldb** [comment]
See https://github.com/basho/riak_dt/pull/102

**Comment by cmeiklejohn** [comment]
Closing; addressed by #102.
