### ISSUE TITLE
Yolozuna extractors

### ISSUE THREAD

**Issue by lenary** [basho/riak_dt#60]
I took a bash at writing some before. We should look again at writing them, especially as the counters one will require updating, and people might want extractors for other types too (sets, maps, bools).

I guess this will land post-2.0 (but for counter compatibility, which may be removed).

**Comment by lenary** [comment]
Extractors landed for 2.0, but this issue was ignored.

**Comment by bookshelfdave** [comment]
Was the Yolo part intentional?

**Comment by lenary** [comment]
of course
